baseURL = 'https://gand-elf.neocities.org/'
languageCode = 'en-us'
title = 'gand_elf place'
theme = 'hugo.386'
description = "Welcome to gand_elf's place, a magical world where i talk a lot."

DefaultContentLanguage = "en" # Change this to change the site's language

preserveTaxonomyNames = true
refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "/not-here-yet"

[params]
    # The name to display as main title in the home page
    mainpagetitle = "gand_elf place"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "gand_elf place !! Le meilleur endroit pour lire mon avis, qui vous interresse surement... \n en ce moment je transfére ce que j'ai déjà écrit donc je vais être plutot actif. Autre info, je reflechis a un designe de naiére animée comme celle du Lainring, si vous avez des idées, @gand_elf sur discord" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "Bienvenue ici... je melange un peu le francais et l'anglais partout sur le site mais oklm, ce que j'écrit est en francais normalement. \n A part le bazard d'unification, je raconte mes experience sur le jeux vidéo, et autre. peut être que je rajouterais d'autres choses plus tard... qui sait ? \n Aussi mon orthographe est surement pas ouf, je fait de mon mieu xpour rendre tout ca intelligible, n'hesitez pas a me le dire (jsp comment...) je serais juste un petit peu vexé."


    # The name to display in the copyright section in the footer
    #copyrightname = "gand_elf"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    #copyrighturl = "http://jmf-portfolio.netlify.com"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 2.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "gand_elf"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    #url = "http://jmf-portfolio.netlify.com"

    # Text to go before copyright information
    prefix = "[hugo.386 theme by Max le Fou](https://gitlab.com/maxlefou/hugo.386)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "inside Lainring"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"       # The path can lead to a content folder too.
    weight = 25

  [[menu.main]]
    identifier = "lainring"
    name = "Lainring"
    url = "/lainring/"
    weight = 30

  [[menu.main]]
    identifier = "9b9tgoals"
    name = "9b9t achievements"
    url = "/9b9tgoal/"
    weight = 40

  [[menu.main]]
    identifier = "guestbook"
    name = "livre d'or/guestbook"
    url = "http://users4.smartgb.com/g/g.php?a=s&i=g44-82905-ab"
    weight = 50
    
[taxonomies]
    tag = "tags"

[markup.goldmark.renderer] 
    unsafe=true

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
