baseURL = 'https://gand-elf.neocities.org/'
languageCode = 'en-us'
title = 'gand_elf place'
theme = 'hugo.386'
description = "Welcome to gand_elf's place, a magical world where i talk a lot."

DefaultContentLanguage = "en" # Change this to change the site's language

preserveTaxonomyNames = true
refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "/not-here-yet"

[params]
    math = true
    # The name to display as main title in the home page
    mainpagetitle = "gand_elf place"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = """La nature semble reprendre ses doits"""

    # The description of your website. It will be displayed in the home page
    mainpagedesc = """Bienvenue ici... je melange un peu le francais et l'anglais partout sur le site mais oklm
    Ce que j'écrit est en francais normalement.
    A part le bazard d'unification, je raconte mes experience sur le jeux vidéo, et autre.
    Peut être que je rajouterais d'autres choses plus tard... qui sait ?
    Aussi mon orthographe est surement pas ouf, je fait de mon mieux pour rendre tout ca intelligible.
    Parlez moi sur Matrix : @gand_elf:federated.nexus"""


    # The name to display in the copyright section in the footer
    copyrightname = "gand_elf"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = "[RSS](https://gand-elf.neocities.org/post/index.xml)"

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Urls for social networks

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 2.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "gand_elf"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://matrix.to/#/@gandelf:federated.nexus"

    # Text to go before copyright information
    prefix = "[Source available on Codeberg](https://codeberg.org/gand_elf/neocities-gandelf-place.git)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "inside Lainring"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "About"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 10          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "All posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 20

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"       # The path can lead to a content folder too.
    weight = 25

  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 27
    identifier = "gallery"
  [[menu.main]]
    name = "World"
    url = "/world/"
    weight = 30
    identifier = "world"

  [[menu.main]]
    identifier = "9b9tgoals"
    name = "9b9t achievements"
    url = "/9b9tgoals/"
    weight = 40
 
  [[menu.main]]
    identifier = "guestbook"
    name = "livre d'or/guestbook"
    url = "/guestbook"
    weight = 50
    
[taxonomies]
    tag = "tags"

[markup.goldmark.renderer] 
    unsafe=true

[markup.goldmark.extensions]
  [markup.goldmark.extensions.passthrough]
    enable = true
    [markup.goldmark.extensions.passthrough.delimiters]
      block = [['\[', '\]'], ['$$', '$$']]
      inline = [['\(', '\)'], ['$', '$']]


[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
