name: Deploy to Neocities

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: codeberg-small
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: https://github.com/peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.161.0'
          extended: true

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy to Neocities
        run: |
          curl -L https://github.com/neocities/neocities-cli/releases/download/3.0.0/neocities-linux-amd64 -o neocities
          chmod +x neocities
          ./neocities deploy -t ${{ secrets.NEOCITIES_API_TOKEN }} public
