name: Deploy to Neocities

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  build:
    runs-on: codeberg-small
    steps:
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: https://github.com/peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.161.0'
          extended: true

      - name: Build with Hugo
        run: hugo --minify

      - name: Deploy to neocities
        uses: https://github.com/bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          neocities_supporter: false
          preview_before_deploy: true
          dist_dir: public
